name: goreleaser

on:
  pull_request:
  push:

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
      -
        name: Build Binaries
        run: | 
          docker run --rm --privileged  --env GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} -v /home/runner/work/cpumem-go-adapter/cpumem-go-adapter:/go/src/github.com/clearblade/cpumem-go-adapter -v /var/run/docker.sock:/var/run/docker.sock -w /go/src/github.com/clearblade/cpumem-go-adapter  mailchain/goreleaser-xcgo release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # - 
      #   name: Run GoReleaser
      #   uses: goreleaser/goreleaser-action@v2
      #   with:
      #     version: latest
      #     args: release --rm-dist
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}